### PR TITLE
Fixed some small spelling mistakes

### PR DESCRIPTION
**Pull request by wermos**

### CODE REVIEW

**Comment by wermos** [comment]
After finding the first few organically (i.e. while reading the book), I decided to go through the whole repo using a spell checker.

I think you would get a lot of value out of a spell-checker, so you might want to look into integrating one into your workflow.

I used [`CSpell` ](https://cspell.org/) to comb through the repo for spelling mistakes. If you already have `npm` or are familiar with how to set that up, you can easily use that too. I can also share the custom word dictionary I used if you're interested (which I just put together, nothing too fancy). Since chess programming has a lot of field-specific jargon, the spell checker returns a lot of false positives.

**Comment by wermos** [comment]
BTW, I've been interested in chess programming for quite some time, since watching a [chess engine competition video](https://youtu.be/Ne40a5LkK6A) by [Sebastian Lague](http://www.youtube.com/@SebastianLague). But the information about chess engine programming on the web is so dispersed and you need to look at so many different sources to get a basic idea of a concept, that I've been putting it on the backburner. Your Rustic book is a great one-stop shop for many of the ideas and a basic roadmap. So, thanks for making this book, and you can rest assured that your book has helped out at least one aspiring chess programmer 😄

That's partly why I made this spelling-mistake-fix PR, it's the least I can do to show my thanks ❤️

**Comment by mvanthoor** [comment]
Hey @wermos ,

Thanks for taking the trouble to fix the spelling mistakes! I've merged the PR and published a new version of the book. I've also been preparing the code samples for some new chapters. I hope I'll get this thing finished and cross it off my bucket-list before I end up in the bucket myself. Darn, this is more work than I expected. Even more than writing the engine itself 😝

**Comment by wermos** [comment]
> I've also been preparing the code samples for some new chapters.

Looking forward to it! And thanks again, for all the effort you've been putting into the book, it's a huge help to a newbie in the field like me.

**Pull request merged**
